FROM plugins/base:linux-arm

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Greenkeeper" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache git nodejs nodejs-npm yarn
RUN npm install -g donny-dont/greenkeeper-lockfile#feat/drone-ci

ADD release/linux/arm/drone-greenkeeper /bin/
ENTRYPOINT ["/bin/drone-greenkeeper"]
