# escape=`
FROM plugins/base:windows-1803

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Greenkeeper" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-greenkeeper.exe C:/bin/drone-greenkeeper.exe
ENTRYPOINT [ "C:\\bin\\drone-greenkeeper.exe" ]
